//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.WebControls;
using System.Web.UI;

public partial class Pages_Default {
    protected global::System.Web.UI.UpdatePanel UpdatePanelMetrics;

    protected global::System.Web.UI.WebControls.Label lblTotalIncidents;
    protected global::System.Web.UI.WebControls.Label lblOpenIncidents;
    protected global::System.Web.UI.WebControls.Label lblCriticalIncidents;
    protected global::System.Web.UI.WebControls.Label lblAvgResolution;

    protected global::System.Web.UI.WebControls.Label lblInjuries;
    protected global::System.Web.UI.WebControls.Label lblOverdueActions;
    protected global::System.Web.UI.WebControls.Label lblPendingActions;
    protected global::System.Web.UI.WebControls.Label lblClosedIncidents;

    protected global::System.Web.UI.WebControls.LinkButton btnRefresh;
    protected global::System.Web.UI.WebControls.Label lblLastUpdate;

    protected global::System.Web.UI.WebControls.HiddenField hfIncidentsByMonth;
    protected global::System.Web.UI.WebControls.HiddenField hfIncidentsByDepartment;
    protected global::System.Web.UI.WebControls.HiddenField hfIncidentsBySeverity;
    protected global::System.Web.UI.WebControls.HiddenField hfTopCategories;

    protected global::System.Web.UI.WebControls.GridView gvRecentIncidents;
}
