//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.WebControls;
using System.Web.UI;

public partial class Pages_IncidentList {
    protected global::System.Web.UI.UpdatePanel UpdatePanelGrid;
    protected global::System.Web.UI.WebControls.Label lblRecordCount;
    protected global::System.Web.UI.WebControls.LinkButton btnExportExcel;
    protected global::System.Web.UI.WebControls.GridView gvIncidents;
    protected global::System.Web.UI.WebControls.Label lblMessage;
    protected global::System.Web.UI.WebControls.Label lblError;
    protected global::Controls_FilterPanel FilterPanel1;
}
