//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.WebControls;
using System.Web.UI;

public partial class Pages_IncidentForm {
    protected global::System.Web.UI.WebControls.Label lblPageTitle;
    protected global::System.Web.UI.WebControls.Panel pnlSuccess;
    protected global::System.Web.UI.WebControls.Label lblSuccess;
    protected global::System.Web.UI.WebControls.Panel pnlError;
    protected global::System.Web.UI.WebControls.Label lblError;

    protected global::System.Web.UI.WebControls.TextBox txtTitle;
    protected global::System.Web.UI.WebControls.TextBox txtDescription;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;

    protected global::System.Web.UI.WebControls.DropDownList ddlSeverity;
    protected global::System.Web.UI.WebControls.TextBox txtIncidentDate;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvIncidentDate;
    protected global::System.Web.UI.WebControls.CustomValidator cvIncidentDate;
    protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

    protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDepartment;
    protected global::System.Web.UI.WebControls.DropDownList ddlLocation;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLocation;
    protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCategory;

    protected global::System.Web.UI.WebControls.CheckBox chkInjuries;
    protected global::System.Web.UI.WebControls.TextBox txtWitnessCount;
    protected global::System.Web.UI.WebControls.RangeValidator rvWitnessCount;
    protected global::System.Web.UI.WebControls.TextBox txtEstimatedCost;

    protected global::System.Web.UI.WebControls.Panel pnlRootCause;
    protected global::System.Web.UI.WebControls.TextBox txtRootCause;

    protected global::System.Web.UI.WebControls.Panel pnlButtons;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnCancel;

    protected global::System.Web.UI.WebControls.Panel pnlIncidentInfo;
    protected global::System.Web.UI.WebControls.Label lblIncidentId;
    protected global::System.Web.UI.WebControls.Label lblCreatedDate;
    protected global::System.Web.UI.WebControls.Label lblLastModified;
    protected global::System.Web.UI.WebControls.Label lblReportedBy;

    protected global::System.Web.UI.WebControls.Panel pnlActions;
    protected global::System.Web.UI.WebControls.GridView gvActions;
}
