//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Controls_FilterPanel {
    protected global::System.Web.UI.UpdatePanel UpdatePanelFilter;
    protected global::System.Web.UI.WebControls.TextBox txtKeyword;
    protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
    protected global::System.Web.UI.WebControls.DropDownList ddlLocation;
    protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
    protected global::System.Web.UI.WebControls.DropDownList ddlSeverity;
    protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
    protected global::System.Web.UI.WebControls.DropDownList ddlDateRange;
    protected global::System.Web.UI.WebControls.Panel pnlCustomDateRange;
    protected global::System.Web.UI.WebControls.TextBox txtStartDate;
    protected global::System.Web.UI.WebControls.TextBox txtEndDate;
    protected global::System.Web.UI.WebControls.LinkButton btnSearch;
    protected global::System.Web.UI.WebControls.LinkButton btnClear;
    protected global::System.Web.UI.WebControls.Label lblResultCount;
}
