//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Controls_IncidentSummary {
    protected global::System.Web.UI.WebControls.Label lblTitle;
    protected global::System.Web.UI.WebControls.Label lblIncidentId;
    protected global::System.Web.UI.WebControls.Label lblIncidentDate;
    protected global::System.Web.UI.WebControls.Label lblDepartment;
    protected global::System.Web.UI.WebControls.Label lblLocation;
    protected global::System.Web.UI.WebControls.Label lblCategory;
    protected global::System.Web.UI.WebControls.Label lblSeverity;
    protected global::System.Web.UI.WebControls.Label lblStatus;
    protected global::System.Web.UI.WebControls.Panel pnlDescription;
    protected global::System.Web.UI.WebControls.Label lblDescription;
    protected global::System.Web.UI.WebControls.HyperLink lnkViewDetails;
    protected global::System.Web.UI.WebControls.HyperLink lnkEdit;
    protected global::System.Web.UI.WebControls.Label lblReportedBy;
}
